name = "gemini-agent"
main = "src/worker.ts"
compatibility_date = "2024-05-28"

[assets]
directory = "./public"
binding = "ASSETS"

[[kv_namespaces]]
binding = "CHAT_HISTORY"
id = "c5478e844e214c958348616df1c39a0c"
preview_id = "75698db100074841b50d3aecc5b96542"
